# TCL File Generated by Component Editor 21.1
# Thu Dec 08 16:48:02 EST 2022
# DO NOT MODIFY


# 
# Avalon_Lamps_Agent "Avalon Lamps Agent" v1.0
# Corbin, Kalvin, Soumil,Victor 2022.12.08.16:48:02
# ADS Project 5 FA 2022
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Avalon_Lamps_Agent
# 
set_module_property DESCRIPTION "ADS Project 5 FA 2022"
set_module_property NAME Avalon_Lamps_Agent
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Corbin, Kalvin, Soumil,Victor"
set_module_property DISPLAY_NAME "Avalon Lamps Agent"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL seven_segment_agent
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file seven_segment_agent.vhd VHDL PATH seven_segment_agent.vhd TOP_LEVEL_FILE
add_fileset_file seven_segment_pkg.vhd VHDL PATH seven_segment_pkg.vhd


# 
# parameters
# 
add_parameter decimal_support BOOLEAN true ""
set_parameter_property decimal_support DEFAULT_VALUE true
set_parameter_property decimal_support DISPLAY_NAME decimal_support
set_parameter_property decimal_support WIDTH ""
set_parameter_property decimal_support TYPE BOOLEAN
set_parameter_property decimal_support UNITS None
set_parameter_property decimal_support DESCRIPTION ""
set_parameter_property decimal_support HDL_PARAMETER true
add_parameter implementer NATURAL 200
set_parameter_property implementer DEFAULT_VALUE 200
set_parameter_property implementer DISPLAY_NAME implementer
set_parameter_property implementer TYPE NATURAL
set_parameter_property implementer ENABLED false
set_parameter_property implementer UNITS None
set_parameter_property implementer HDL_PARAMETER true
add_parameter revision NATURAL 0
set_parameter_property revision DEFAULT_VALUE 0
set_parameter_property revision DISPLAY_NAME revision
set_parameter_property revision TYPE NATURAL
set_parameter_property revision ENABLED false
set_parameter_property revision UNITS None
set_parameter_property revision HDL_PARAMETER true
add_parameter signed_support BOOLEAN true
set_parameter_property signed_support DEFAULT_VALUE true
set_parameter_property signed_support DISPLAY_NAME signed_support
set_parameter_property signed_support TYPE BOOLEAN
set_parameter_property signed_support UNITS None
set_parameter_property signed_support HDL_PARAMETER true
add_parameter blank_zeros_support BOOLEAN true
set_parameter_property blank_zeros_support DEFAULT_VALUE true
set_parameter_property blank_zeros_support DISPLAY_NAME blank_zeros_support
set_parameter_property blank_zeros_support TYPE BOOLEAN
set_parameter_property blank_zeros_support UNITS None
set_parameter_property blank_zeros_support HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point digits
# 
add_interface digits conduit end
set_interface_property digits associatedClock clock
set_interface_property digits associatedReset ""
set_interface_property digits ENABLED true
set_interface_property digits EXPORT_OF ""
set_interface_property digits PORT_NAME_MAP ""
set_interface_property digits CMSIS_SVD_VARIABLES ""
set_interface_property digits SVD_ADDRESS_GROUP ""

add_interface_port digits digits export Output 42

